trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
- task: CmdLine@2
  inputs:
    script: |
      git submodule update --init --recursive
      git submodule update --remote --merge
  displayName: 'Checkout'

- task: CmdLine@2
  inputs:
    script: |
      cd ..
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      ./emsdk install latest
  displayName: 'Clone/install emsdk'

- task: CmdLine@2
  inputs:
    script: |
      pushd ../emsdk
      ./emsdk activate latest
      source "emsdk_env.sh"
      popd
      cd recastjs
      mkdir build
      emcmake cmake -B build -DCMAKE_BUILD_TYPE=Release
      cmake --build build
      mkdir package
      cp ./package.json ./package
      cp ./readme.md ./package
      cp ./License.txt ./package
      cp ./recast.d.ts ./package
      cp ./build/recast.es6.js ./package
      cp ./build/recast.js ./package
      cp ./build/recast.wasm.js ./package
      cp ./build/recast.wasm.wasm ./package
  displayName: 'Build package'

- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'recastjs/package'
    publishEndpoint: 'NPMWithAccessToken'