name: Build Recast
on: workflow_dispatch
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.3
      - name: Update submodule
        run: |
             git submodule update --init --recursive
             git submodule update --remote --merge
      - name: Clone/install emsdk
        run: |
             cd ..
             git clone https://github.com/emscripten-core/emsdk.git
             cd emsdk
             ./emsdk install latest
      - name: Build
        run: |
             cd ../emsdk
             ./emsdk activate latest
             source "emsdk_env.sh"
             cd ../Extensions/recastjs
             mkdir build
             emcmake cmake -B build -DCMAKE_BUILD_TYPE=Release
             cmake --build build
             mkdir Package
             cp ./Package.json ./Package
             cp ./readme.md ./Package
             cp ./build/recast.js ./Package
             cp ./build/recast.wasm.js ./Package
             cp ./build/recast.wasm.wasm ./Package

      - name: Upload Recast Package Folder
        uses: actions/upload-artifact@v2
        with:
          name: 'recast package'
          path: recastjs/Package